"""Generate the project's codeless USD schemas from one auditable definition."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
SCHEMAS={
'CardboardScenarioAPI': '''
    float3 cardboard:homeOffset = (-0.22, 0, 0.24)
    float cardboard:approachClearance = 0.20
    float cardboard:liftHeight = 0.12
    float3 cardboard:graspTiltDegrees = (0, 0, 0)
    float3 cardboard:liftTiltDegrees = (0, 0, 0)
    float3 cardboard:crushTiltDegrees
    float3 cardboard:releaseTiltDegrees
    float cardboard:graspGap = 0.255
    float cardboard:crushGap = 0.11
    float cardboard:graspForce = 18
    float cardboard:crushForce = 70
    float cardboard:crushRampFraction = 0.65
    float cardboard:releaseRampFraction = 1
    float[] cardboard:phaseEnds = [1, 3, 5, 7, 9, 12, 13, 16]
''',
'CardboardMaterialAPI': '''
    float cardboard:thickness = 0.003
    float cardboard:arealDensity = 0.65
    float cardboard:membraneShear = 12600
    float cardboard:membraneArea = 21000
    float cardboard:membraneDamping = 0.0002
    float cardboard:bendingMD = 0.042
    float cardboard:bendingCD = 0.02016
    float cardboard:yieldCurvature = 12
    float cardboard:hardeningRatio = 0.02
    float cardboard:damageRate = 0.35
    float cardboard:residualStiffness = 0.25
    float cardboard:bendingDamping = 0.0002
    float cardboard:bendingReferenceThickness = 0.003
    float cardboard:bendingThicknessExponent = 0
    float cardboard:bendingRelaxationTime = 0
    float cardboard:selfContactThicknessScale = 0.5
    float cardboard:friction = 0.65
    bool cardboard:plasticityEnabled = true
    token cardboard:calibrationStatus = "illustrativeUncalibrated"
''',
'CardboardShellAPI': '''
    uint cardboard:schemaVersion = 1
    token cardboard:solver = "newtonVBD15"
    point3f[] cardboard:restPoints
    int4[] cardboard:hingeIndices
    float[] cardboard:referenceAngles
    float[] cardboard:dualWidths
    float[] cardboard:edgeStiffness
    float3[] cardboard:materialDirection
    rel cardboard:material
    rel cardboard:renderMesh
    asset cardboard:sourceAsset
    float cardboard:sourceScale = 0.4
''',
'CardboardPlasticStateAPI': '''
    float[] cardboard:plasticAngles
    float[] cardboard:accumulatedAngles
    float[] cardboard:plasticDissipation
    float[] cardboard:damage
    vector3f[] cardboard:velocities
''',
'CardboardBindingAPI': '''
    token cardboard:surfaceInterpolation = "linear"
    float cardboard:visualCreaseAngleDegrees = 45
    float cardboard:visualCreaseTransitionDegrees = 10

    rel cardboard:simulationMesh
    int3[] cardboard:bindingIndices
    float3[] cardboard:bindingWeights
    vector3f[] cardboard:bindingOffsets
''',
'CardboardDemoAPI': '''
    float cardboard:fps = 60
    int cardboard:substeps = 16
    int cardboard:iterations = 16
    bool cardboard:rigidCompliantALM = false
    bool cardboard:kinematicArm = false
    bool cardboard:precomputeCommands = false
    bool cardboard:realtimePacing = false
    bool cardboard:translationBlockSolve = false
    float cardboard:duration = 11
    float cardboard:gravityRampSeconds = 0
    float cardboard:contactStiffness = 20000
    float cardboard:contactDamping = 0.1
    float cardboard:maxFingerForce = 30
    float cardboard:fingerPositionStiffness = 1200
    float cardboard:fingerVelocityDamping = 12
    float cardboard:openGap = 0.32
    float cardboard:minimumGap = 0.16
    float cardboard:twistRadians = 0.12
    float cardboard:maxWristTorque = 2
    rel cardboard:box
    rel cardboard:robot
    rel cardboard:fingerJoints
'''}
types={'Usd'+n:{'schemaIdentifier':n,'alias':{'UsdSchemaBase':n},'autoGenerated':False,'bases':['UsdAPISchemaBase'],'schemaKind':'singleApplyAPI'} for n in SCHEMAS}
r=ROOT/'schemas/cardboard/resources';r.mkdir(parents=True,exist_ok=True)
(r/'plugInfo.json').write_text(json.dumps({'Plugins':[{'Type':'resource','Name':'CardboardSchemas','Root':'..','ResourcePath':'resources','Info':{'Types':types}}]},indent=2))
(r/'generatedSchema.usda').write_text('#usda 1.0\n\n'+ '\n'.join('class "'+n+'"\n{\n'+v+'}\n' for n,v in SCHEMAS.items()))
(ROOT/'schemas/cardboard/schema.usda').write_text('#usda 1.0\n( subLayers = [@usd/schema.usda@] )\nover "GLOBAL" (customData = {string libraryName = "cardboardSchemas" bool skipCodeGeneration = true}) {}\n'+ '\n'.join('class "'+n+'" (inherits = </APISchemaBase> customData = {token apiSchemaType = "singleApply"})\n{\n'+v+'}\n' for n,v in SCHEMAS.items()))
print('Wrote',len(SCHEMAS),'codeless schemas')
