"""Generate codeless USD schemas from the canonical schema.usda definitions."""
import argparse
import json
from pathlib import Path
from pxr import Sdf

ROOT = Path(__file__).resolve().parents[1]

def main():
    parser=argparse.ArgumentParser(__doc__);parser.add_argument('--check',action='store_true');args=parser.parse_args()
    source=Sdf.Layer.FindOrOpen(str(ROOT/'schemas/cardboard/schema.usda'))
    generated=Sdf.Layer.CreateAnonymous();names=[]
    for prim in source.rootPrims:
        if prim.name=='GLOBAL':continue
        names.append(prim.name)
        Sdf.CopySpec(source,prim.path,generated,prim.path)
        copy=generated.GetPrimAtPath(prim.path);copy.inheritPathList.ClearEdits();copy.customData={}
    types={'Usd'+n:{'schemaIdentifier':n,'alias':{'UsdSchemaBase':n},'autoGenerated':False,'bases':['UsdAPISchemaBase'],'schemaKind':'singleApplyAPI'} for n in names}
    outputs={'generatedSchema.usda':generated.ExportToString(),'plugInfo.json':json.dumps({'Plugins':[{'Type':'resource','Name':'CardboardSchemas','Root':'..','ResourcePath':'resources','Info':{'Types':types}}]},indent=2)+'\n'}
    folder=ROOT/'schemas/cardboard/resources'
    for name,content in outputs.items():
        path=folder/name
        if args.check:
            if path.read_text()!=content:raise SystemExit('Stale generated schema: '+str(path))
        else:path.write_text(content)
    print(('Verified' if args.check else 'Wrote'),len(names),'codeless schemas')

if __name__=='__main__':main()
