"""Aggregate final evidence without changing any validation threshold."""
import hashlib,json,re
from pathlib import Path
from cardboard import ROOT
out=ROOT/'outputs/robotiq_board10';evidence=ROOT/'outputs/stability_speed'
asset=json.loads((evidence/'board10_asset_validation.json').read_text())
sequence=json.loads((out/'validation.json').read_text());crease=json.loads((out/'crease_comparison.json').read_text());rest=json.loads((out/'supported_rest_validation.json').read_text())
unit=(evidence/'unit_tests.log').read_text();gui=(evidence/'gui_test.log').read_text()
checks={'dimensional_geometry':asset['passed'],'sequence':sequence['passed'],'crease_recoil':crease['passed'],'supported_rest_and_speed':rest['passed'],'unit_tests':bool(re.search(r'Ran 43 tests',unit) and '\nOK\n' in unit),'gui_controls':'CONTROL_TEST play/pause/reset/replay PASS' in gui,'gui_recorded_replay':'RECORDED_REPLAY pause/resume/final-frame PASS' in gui}
paths=['src/cardboard/simulation.py','src/cardboard/block_solver.py','src/cardboard/compact_contact.py','src/cardboard/rotation_block.py','src/cardboard/rigid_subspace.py','src/cardboard/internal_damping.py','src/cardboard/resting.py','src/cardboard/surface.py','scripts/build_board10_stable.py','scripts/live_isaac.py','scripts/stream_newton.py','assets/demo_scene_robotiq_board10.usda','assets/cardboard_robotiq_board10.usda','outputs/robotiq_board10/trajectory.npz']
report={'passed':all(checks.values()),'checks':checks,'counts':{'unit':43,'asset':len(asset['checks']),'sequence':len(sequence['checks']),'crease':len(crease['checks']),'rest_speed':len(rest['checks'])},'thickness_mm':asset['thickness_mm'],'physical_vertices':asset['physical_vertices'],'physical_triangles':asset['physical_triangles'],'display_triangles':asset['render_triangles'],'mass_kg':asset['mass_kg'],'baseline_wall_s':rest['baseline_wall_s'],'candidate_wall_s':rest['candidate_wall_s'],'speedup':rest['speedup'],'sleep_events':rest['sleep_events'],'side_motion':rest['candidate_side_motion'],'final_speed_m_s':sequence['final_speed_m_s'],'supported_internal_damping_per_s':json.loads((out/'run_config.json').read_text())['supported_internal_damping_rate'],'qualification':'Combined requested gauge change and solver optimization; not a bit-identical physics benchmark. Active wall includes diagnostics/snapshots, excludes model/GUI startup. Supported damping and sleep are explicit approximate dissipative rest controls, not measured cardboard calibration. No display-frame freeze.','sha256':{p:hashlib.sha256((ROOT/p).read_bytes()).hexdigest() for p in paths}}
(evidence/'final_validation.json').write_text(json.dumps(report,indent=2)+'\n');print(json.dumps(report,indent=2));raise SystemExit(0 if report['passed'] else 1)
